# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84dc8b9c761534169cdbf469fdec9dde96ed63b6d3c61e8f69fa5de61783fae2cf39b26cb5ffa8991a53991132101509807d021273f96a08421fe094acc218bb

test:
  secret_key_base: 33f7192b914995472f151a63114ee5d3486f331afc049cbf2c4c79b4083ab1b9d0099c4508ee02e767fd5932203f729699a53dc59138806999d10b82443cd029

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
